# 設定安裝SonarQube所需資料庫環境
- hosts: ci_cd_test
  remote_user: petercheng
  become: yes
  become_user: postgres
  tasks:
    - name: "設定SonarQube所需資料庫環境"
      include_tasks: tasks/config/postgres.yml

# 設定SonarQube相關設定
- hosts: ci_cd_test
  remote_user: petercheng
  become: yes
  become_user: root
  tasks:
    - name: "設定SonarQube相關設定"
      include_tasks: tasks/config/sonarQube.yml