---
- hosts: ci_cd_test
  remote_user: petercheng
  become: yes
  tasks:
    # 初始化系統
    - name: "全系統更新"
      include_tasks: tasks/install/init.yml
    - name: "安裝Git"
      include_tasks: tasks/install/git.yml

    # 安裝Golang 1.13.4
    - name: "安裝Golang 1.13.4"
      include_tasks: tasks/install/golang.yml

    # 安裝Docker
    - name: "安裝Docker"
      include_tasks: tasks/install/docker.yml

    # 安裝Docker-Compose
    - name: "安裝Docker"
      include_tasks: tasks/install/docker-compose.yml