---
- name: "安裝PostgreSQL"
  apt:
    pkg: 
      - postgresql
      - python-psycopg2
    state: present
    update_cache: yes
- name: "修改資料庫管理員預設密碼"
  user:
    name: postgres
    password: "{{ '1qazse4rfvgy7' | password_hash('sha512') }}"