---
  #安裝SonarQube
  - name: "移除舊版SonarQube壓縮包"
    file: 
      path: /tmp/sonarQube-LTS.zip
      state: absent
  - name: "移除舊版SonarQube安裝包"
    file:
      path: /opt/sonarqube
      state: absent
  - name: "下載SonarQube"
    get_url: 
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip
      dest: /tmp/sonarQube-LTS.zip
      mode: 444
  - name: "安裝Unzip套件"
    apt:
      pkg:
        - unzip 
        - openjdk-11-jdk
        - openjdk-11-jdk-headless
      state: present
  - name: "解壓SonarQube"
    unarchive: 
      src: /tmp/sonarQube-LTS.zip
      dest: /opt
      remote_src: yes
  - name: "修改目錄名稱"
    command: mv /opt/sonarqube-7.9.1 /opt/sonarqube